branches:
  only:
  - master
  - dev
  - /^v.*$/
language: python
jobs:
  include:
  - name: Python 3.7.4 on macOS
    os: osx
    osx_image: xcode11.2
    language: shell
  - name: Python 3.5 on Xenial Linux
    python: 3.5
  - name: Python 3.6 on Xenial Linux
    python: 3.6
  - name: Python 3.7.4 on Xenial Linux
    python: 3.7.4
  - name: Python 3.8 on Xenial Linux
    python: 3.8
before_install:
- python3 --version
install:
- pip3 install --upgrade pip
- pip3 install . -r requirements.txt
- pip3 install codecov==2.0.15 pytest==5.3.1 coverage==4.5.4 pytest-cov==2.8.1
script:
- python3 -m coverage run -m pytest --cov=ncbimeta --cov-report=xml test/test_errors.py
  test/test_utilities.py test/test_ncbimeta.py test/test_annotateconcatenate.py test/test_annotatereplace.py
  test/test_join.py test/test_export.py
- NCBImeta.py --flat --config example/config.yaml
- NCBImetaAnnotateReplace.py --database example/yersinia_pestis_db.sqlite --annotfile
  example/annot.txt --table BioSample
- NCBImetaAnnotateConcatenate.py --database example/yersinia_pestis_db.sqlite --annotfile
  example/annot.txt --table BioSample
- NCBImetaJoin.py --database example/yersinia_pestis_db.sqlite --anchor BioSample
  --accessory "BioProject Assembly SRA Nucleotide" --final Master --unique "BioSampleAccession
  BioSampleAccessionSecondary BioSampleBioProjectAccession"
- NCBImetaExport.py --database example/yersinia_pestis_db.sqlite --outputdir example/
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: ${GITHUB_USER}
  password:
    secure: yDyygOrB0wtkeYPOVHPYN45waTXdenAC9kBac778/z9TTEYIdXjLTaYEJFkDzQeiH7ykH09OVdpkL6Z+YbzE6oFxuZzEWZ906MX2uT26BUsGIjXa3yIJrMw7aqQC8/Q8wYZBoM2KA/63ur/vxuMfju/Q6lDQvaA14+Nt+u20pyNHFwB/cGGNJdH/wAbgANVQ7QW88fVyUublDo3zONw8VYuLZaTePcMQnglmSva68KhUskDFO6Fz+yCzzBEqiUsbEIXs0etGkq4aPoHDq5esYE/6d/ql2jmhDTRRBrYQsnoCbXIDbafPij85djV3b+TWtoONlW1uDkqUq+22F8dA/nR4QSg8+l3JkKb4cyR5CINC/3JR/AobkwtFcmLcXAiQG5oN5QjqIPuW5X2fcPoQjsoalkDBhpxX0Aj2T9l/h/52++2I5L9N+aWzGb7TrFArGL9nlMsrfz9CK+J6GqUPDMU7v6w/UGJal11k6l3PatAEozbaMpE1iXQwiyiehpE0p4u8dLl3R54Fb+tMwS2xvIol4uRUSFn//aWdPMM2Z5jg5p5w4xiAUBMZR2vM0WIdU6PSfoel4tZlxzH99EOCjpx6CTEhCvpnwfaYkOaHLmFl8zu6lIKRsru6q3hexVSbWqudpOT6RHI3B9JrKPkLbklYsTf0E7M6ehcPsbHLTmE=
  skip_existing: true
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_PYTHON_VERSION = 3.5
    tags: true
notifications:
  slack:
    on_pull_requests: true
    on_success: always
    on_failure: always
    rooms:
    - secure: KLCMg7vubNuaaQUH4VpbBQhxH4VMSdYhe2GEMeaaCvbeOAUx0ODSYCrpYBDTCbUhLxVoa6Efk7wK7G/mBjvVEFI+X/rrXikRJtUonWYI3Xh7tZCNEveglULjmbcN1kCdCpj2Ola7e3CnclcfZrP7uFXD3M2lt3/651cfIGmH3Wdj4tklBslSV3R2bguUsevhmQ7aqFpHPABwcpZA/IbSgTVwCN8+zpTQgbr9X7aGGY1hkdV+lHAROFLYThSa2NWgU95DrADtWdvLHVMbYFone4Jg2WXSPJFXQ5GqlWuiRzFPE59NNSCZJ9eAiQpiOOVl4j1wjMYsU9oC9olbJbC/GZiEQGqF+PRjzAehCAoFNIZQIV+42lbPuEkIJP2yTdED1E7MU52CvQ75670stTyv8K2xDiOTqN1mqQRoyLovdKFwvc1uunr7v3wMh1xdL9UVmZ6uMlF/LVshtOeHzqQB8f3TSf8hW1918Y1D7eZIjIiwiXcj2H6fYy27N2pglOL6vmdzHnFwK8/PS75A4Rf4isbsl+r2h+n6pI1g3LoRHDCHbk5KKPE3RTX/I7y4t4alP2sEP/dY3uU00aoQX0RCDGCX7ff2WWkBCaqv7mrrFtl41kY69Pn01Lu1TiaF5TSbc3wgoPwzMmyqT+1iFSIBWNqF5TzdbTB7B5kF8HREtrM=
