name: Lint
#This is a workflow for linting

on:
  # Triggered on Push for all branches
  push:
    branches:
      - '*'
    # On change to workflow, markdown, python
    paths:
      - '.github/workflows/*.yaml'
      - '.github/*.yaml'
      - 'schema/*.yaml'
      - 'example/*.yaml'
      - '*.md'
      - 'config/*md'
      - 'schema/*md'
      - ncbimeta/*.py
      - test/*.py
  # Triggered on PR for all branches, any file
  pull_request:
    branches:
      - '*'

jobs:

  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install pre-commit Dependencies
        run: |
          pip install pre-commit
          pre-commit install-hooks
      - name: pre-commit Linting
        run: pre-commit run --all-files

  # Use the template python package linting
  python_lint:
    needs: pre_commit
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.5'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-bugbear
      - name: Lint with flake8
        run: |
          flake8 ${GITHUB_WORKSPACE} --config ${GITHUB_WORKSPACE}/setup.cfg

  # Markdown template from nf-core eager to trial
  markdown_lint:
    needs: pre_commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Run Markdownlint
        run: markdownlint ${GITHUB_WORKSPACE} --config ${GITHUB_WORKSPACE}/.github/markdown_lint.yaml --ignore paper/

  # YAML Lint To-Do
